### ISSUE TITLE
Allow styling external links

### ISSUE THREAD

**Issue by phijor** [jonahgoldwastaken/mdbook-external-links#3]
I'm writing a book and I want to visually and functionally distinguish external from internal links.  Your plugin helps me achieve the functionality. Now I also want to style external links. I reckon this could be trivially supported by...

1. Adding a `class="external-link"` to `<a>` tags in addition to `target="_blank"`
2. Letting the user write some custom CSS, such as
    ```css
    a.external-link::after {
      font-family: FontAwesome;
      content: "\f08e"; /* fa-external-link */
      display: inline-block;
      padding-left: 3px;
      vertical-align: middle;
    }
    ```

Do you think this is a sensible addition to the plugin?
